### ISSUE TITLE
Install Redis Insight on Kubernetes with persistant storage geting permissions denied

### ISSUE THREAD

**Issue by ongtungduong** [redis/docs#176]
[Install Redis Insight on K8S](https://redis.io/docs/latest/operate/redisinsight/install/install-on-k8s/
)
```
      initContainers:
        - name: init
          image: busybox
          command:
            - /bin/sh
            - '-c'
            - |
              chown -R 1001 /data  
```
chown command has wrong UID to give permissions to access the volume provided. It must be 1000 refer to [Install Redis Insight on Docker](https://redis.io/docs/latest/operate/redisinsight/install/install-on-docker/)
